<?php
/**
 * Created by PhpStorm.
 * User: David
 * Date: 05.03.2019
 * Time: 17:20
 */

namespace Davajlama\SchemaBuilder\Driver\SQLite;


class Inspector extends \Davajlama\SchemaBuilder\Driver\MySql\Inspector
{

    public function describeTable($name)
    {
        //return parent::describeTable($name); // TODO: Change the autogenerated stub
        throw new \Exception("Not implemented yet!");
    }

    public function existsTable($name)
    {
        //return $this->getAdapter()->fetchAll("SELECT * FROM main.sqlite_master WHERE type='$name'");
        return [];
    }

    public function showIndexes($table)
    {
        //return parent::showIndexes($table); // TODO: Change the autogenerated stub
        throw new \Exception("Not implemented yet!");
    }

}